version: '3'
services:
  node-app:
    build: .
    # ports:
    #   - 8080:8080
    env_file:
      - ./.env
  redis:
    image: redis:7.0.2-alpine
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - node-app
    ports:
      - "80:80"
    
